{{ range .Values.users -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ regexReplaceAll "[_\\W]" . "" | trunc 15 }}-{{ . | sha256sum | trunc 8 }}
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: rhods-notebook
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    helm:
      values: |
        user: {{ . }}
        user_urlencoded: {{ . | replace "_" "-5f" | replace "-" "-2d" | replace "@" "-40" | replace "." "-2e" }}
        resource_name: {{ regexReplaceAll "[_\\W]" . "" | trunc 15 }}-{{ . | sha256sum | trunc 8 }}
        workbench_name: {{ $.Values.workbench_name }} 
        base_domain: {{ $.Values.base_domain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: kubeflow.org
    kind: Notebook
    jqPathExpressions:
    - .spec.template.spec.containers[] | select(.name == "oauth-proxy")
  - group: kubeflow.org
    kind: Notebook
    jqPathExpressions:
    - .spec.template.spec.volumes[] | select(.name == "oauth-config")
  - group: kubeflow.org
    kind: Notebook
    jqPathExpressions:
    - .spec.template.spec.volumes[] | select(.name == "tls-certificates")
{{ end }}
