---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.{{ .Values.base_domain }}/projects/{{ .Values.resource_name }}?notebookLogout={{ .Values.workbench_name}}
    opendatahub.io/link: https://{{ .Values.workbench_name }}-{{ .Values.resource_name }}.{{ .Values.base_domain }}/notebook/{{ .Values.resource_name }}/{{ .Values.workbench_name }}
    opendatahub.io/username: {{ .Values.user }}
  labels:
    app: {{ .Values.workbench_name }}
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: {{ .Values.user_urlencoded }}
  name: {{ .Values.workbench_name }}
  namespace: {{ .Values.resource_name }}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: nvidia.com/gpu.present
                operator: NotIn
                values:
                - "true"
            weight: 1
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/{{ .Values.resource_name }}/{{ .Values.workbench_name }}
                              --ServerApp.quit_button=False
                              --ServerApp.tornado_settings={"user":"{{ .Values.user_urlencoded }}","hub_host":"https://rhods-dashboard-redhat-ods-applications.{{ .Values.base_domain }}","hub_prefix":"/projects/{{ .Values.workbench_name }}"}
        - name: JUPYTER_IMAGE
          value: {{ .Values.notebook.image }}
        - name: JUPYTER_NOTEBOOK_PORT
          value: "8888"
        image: {{ .Values.notebook.image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Values.resource_name }}/{{ .Values.workbench_name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Values.workbench_name }}
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Values.resource_name }}/{{ .Values.workbench_name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "{{ .Values.notebook.resources.limits.cpu }}"
            memory: {{ .Values.notebook.resources.limits.memory }}
          requests:
            cpu: "{{ .Values.notebook.resources.requests.cpu }}"
            memory: {{ .Values.notebook.resources.requests.memory }}
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: {{ .Values.workbench_name }}
        workingDir: /opt/app-root/src
      enableServiceLinks: false
      serviceAccountName: {{ .Values.workbench_name }}
      volumes:
      - name: {{ .Values.workbench_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.workbench_name }}

