apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: jupyterhub-nb-{{ .Values.user_urlencoded }}-pvc
  namespace: rhods-notebooks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.notebook.storage.size }}
  storageClassName: {{ .Values.notebook.storage.class }}
  volumeMode: Filesystem
