apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    opendatahub.io/dashboard: "true"
  name: {{ .Values.workbench_name }}
  namespace: {{ .Values.resource_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.notebook.storage.size }}
  storageClassName: {{ .Values.notebook.storage.class }}
  volumeMode: Filesystem
