apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhods-view
  namespace: {{ .Values.resource_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhods-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.user }}