apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhods-view
  namespace: {{ .Values.resource_name }}
rules:
- apiGroups:
  - datasciencepipelinesapplications.opendatahub.io
  resources:
  - datasciencepipelinesapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - servingruntimes
  verbs:
  - get
  - list
  - watch
# This is needed for notebook re-launch if it's put to sleep.
# The setting "stop idle notebooks" effectively adds an annotation
# to the notebook "kubeflow-resource-stopped: <timestamp>". 
# If the annotation is present, the StatefulSet is scaled to 0.
# If it's gone - back to 1.
# The stopping is done by rhods' service account, but to re-launch
# our user has to be able to update or patch the notebook.
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update