apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhods-view
  namespace: {{ .Values.resource_name }}
rules:
- apiGroups:
  - datasciencepipelinesapplications.opendatahub.io
  resources:
  - datasciencepipelinesapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - servingruntimes
  verbs:
  - get
  - list
  - watch
