apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: jupyter-nb-{{ .Values.user_urlencoded }}-notebook-view
  namespace: rhods-notebooks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyter-nb-{{ .Values.user_urlencoded }}-notebook-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.user }}
